# AUTO-GENERATED by generate_cicd.py — smoke tests run against live staging/production
import os
import pytest
import httpx

BASE_URL = os.environ.get("BASE_URL", "http://localhost:8080")


def test_liveness():
    r = httpx.get(f"{BASE_URL}/health/live", timeout=10)
    assert r.status_code == 200, f"Liveness probe failed: {r.text}"


def test_readiness():
    r = httpx.get(f"{BASE_URL}/health/ready", timeout=10)
    assert r.status_code == 200, f"Readiness probe failed: {r.text}"


def test_root_responds():
    r = httpx.get(f"{BASE_URL}/", timeout=10)
    assert r.status_code < 500, f"Root endpoint returned 5xx: {r.text}"
