# AUTO-GENERATED by generate_cicd.py — replace with your application code
from fastapi import FastAPI
from fastapi.responses import JSONResponse

app = FastAPI(title="my-app")


@app.get("/health/live")
def liveness():
    return {"status": "alive"}


@app.get("/health/ready")
def readiness():
    # Add real dependency checks here (DB, cache, etc.)
    return {"status": "ready"}


@app.get("/metrics")
def metrics():
    # Replace with prometheus_client exposition
    return {"requests_total": 0}


@app.get("/")
def root():
    return {"app": "my-app", "status": "running"}
