#!/usr/bin/env bash
# AUTO-GENERATED by generate_cicd.py
# Bootstrap ArgoCD + Argo Rollouts. Run once per cluster.
set -euo pipefail

ARGOCD_VERSION="${ARGOCD_VERSION:-v2.13.0}"
ARGO_ROLLOUTS_VERSION="${ARGO_ROLLOUTS_VERSION:-v1.7.0}"

echo "==> Installing ArgoCD"
kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -n argocd \
  -f "https://raw.githubusercontent.com/argoproj/argo-cd/${ARGOCD_VERSION}/manifests/install.yaml"
kubectl rollout status deployment/argocd-server -n argocd --timeout=180s

echo "==> Installing Argo Rollouts"
kubectl create namespace argo-rollouts --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -n argo-rollouts \
  -f "https://github.com/argoproj/argo-rollouts/releases/download/${ARGO_ROLLOUTS_VERSION}/install.yaml"

echo "==> Creating namespaces"
kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -
kubectl create namespace production --dry-run=client -o yaml | kubectl apply -f -

echo "==> Applying ArgoCD Applications"
kubectl apply -f argocd/app-staging.yaml
kubectl apply -f argocd/app-production.yaml
kubectl apply -f argocd/analysis-template.yaml -n production

echo ""
echo "ArgoCD password: $(kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath='{.data.password}' | base64 -d)"
echo "Port-forward:    kubectl port-forward svc/argocd-server -n argocd 8080:443"
