#!/usr/bin/env bash
# AUTO-GENERATED by generate_cicd.py
# Interactive helper to set GitHub Actions secrets for this pipeline.
# Requires: gh (GitHub CLI), already authenticated.

set -euo pipefail

REPO="${GITHUB_REPO:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"
echo "Setting secrets for: $REPO"
echo ""

set_secret() {
    local name="$1"
    local prompt="$2"
    local default="${3:-}"
    if [ -n "$default" ]; then
        read -r -p "  $name [$prompt] (default: $default): " val
        val="${val:-$default}"
    else
        read -r -s -p "  $name [$prompt]: " val
        echo
    fi
    if [ -n "$val" ]; then
        echo "$val" | gh secret set "$name" --repo "$REPO"
        echo "  -> $name set."
    else
        echo "  -> $name skipped."
    fi
}

echo "=== GitOps ==="
set_secret GITOPS_REPO     "org/repo for manifest updates"   "YOUR_ORG/YOUR_GITOPS_REPO"
set_secret GITOPS_TOKEN    "GitHub PAT with repo write access"

echo ""
echo "=== ArgoCD ==="
set_secret ARGOCD_SERVER   "ArgoCD server hostname"
set_secret ARGOCD_TOKEN    "ArgoCD API token"

echo ""
echo "=== Environment URLs ==="
set_secret STAGING_BASE_URL    "Staging base URL"
set_secret PRODUCTION_BASE_URL "Production base URL"

echo ""
echo "=== AI Evals ==="
set_secret ANTHROPIC_API_KEY   "Anthropic API key for eval judge"

echo ""
echo "=== Cloud: aws ==="
set_secret AWS_ROLE_ARN     "IAM role ARN for OIDC auth"
set_secret AWS_REGION       "AWS region"          "us-east-1"
set_secret EKS_CLUSTER_NAME "EKS cluster name"

echo ""
echo "All secrets configured. Run 'gh secret list --repo $REPO' to verify."
