# AUTO-GENERATED by generate_cicd.py — replace with real tests
import pytest
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_liveness():
    r = client.get("/health/live")
    assert r.status_code == 200
    assert r.json()["status"] == "alive"


def test_readiness():
    r = client.get("/health/ready")
    assert r.status_code == 200


def test_root():
    r = client.get("/")
    assert r.status_code == 200
